	class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class Turrets: Turrets
				{
					class CommanderOptics: CommanderOptics
					{
						body="side_turret_l";
						gun="side_gun_l";
						proxyIndex=4;
						viewGunnerInExternal=0;
						proxytype="CPCommander";
						gunnername="Side Gunner";
						animationSourceBody="ObsTurret";
						animationSourceGun="ObsGun";
						minElev=-20;
						maxElev=30;
						minTurn=-25;
						maxTurn=25;
						initElev=0;
						initTurn=0;
						minOutElev=-25;
						maxOutElev=45;
						initOutElev=0;
						minOutTurn=-90;
						maxOutTurn=90;
						initOutTurn=0;
						maxHorizontalRotSpeed=1.8;
						maxVerticalRotSpeed=1.8;
						stabilizedInAxes=3;
						soundServo[]=
						{
							"A3\Sounds_F\vehicles\armor\noises\servo_best",
							0.0099999998,
							1,
							50
						};
						gunnerAction="";
						gunnerInAction="mbt2_slot2b_in";
						forceHideGunner=0;
						outGunnerMayFire=1;
						inGunnerMayFire=1;
						gunnerRightHandAnimName="";
						gunnerLeftHandAnimName="";
						soundAttenuationTurret="HeliAttenuationGunner";
						isPersonTurret=1;
						personTurretAction="vehicle_turnout_1";
						memoryPointGun[]=
						{
							"konec_hlavne_1",
							"konec_hlavne_2"
						};
						weapons[]=
						{
							"442_aat_127"
						};
						magazines[]=
						{
							"442_127x99_500rnd_blue_mag",
							"442_127x99_500rnd_blue_mag"
						};
						turretInfoType="RscWeaponRangeZeroing";
						discreteDistance[]={100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500};
						discreteDistanceInitIndex=2;
						memoryPointGunnerOptics="commanderview";
						memoryPointGunnerOutOptics="commanderview";
						gunnerOpticsModel="\A3\weapons_f\reticle\Optics_Commander_02_F";
						gunnerOutOpticsModel="";
						gunnerOpticsEffect[]={};
						gunnerHasFlares=1;
						turretfollowfreelook=1;
						class OpticsIn
						{
							class Wide: ViewOptics
							{
								initAngleX=0;
								minAngleX=-8;
								maxAngleX=8;
								initAngleY=0;
								minAngleY=-45;
								maxAngleY=80;
								initFov=0.30000001;
								minFov=0.30000001;
								maxFov=0.30000001;
								visionMode[]=
								{
									"Normal",
									"Ti"
								};
								thermalMode[]={4,5};
								gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Gunner_MTB_02_w_F.p3d";
								gunnerOpticsEffect[]={};
							};
						};
						gunnerGetInAction="GetInHigh";
						gunnerGetOutAction="GetOutHigh";
						startEngine=1;
						LODTurnedOut="VIEW_GUNNER";
						LODTurnedIn="VIEW_GUNNER";
						class HitPoints
						{
							class HitTurret
							{
								armor=0.80000001;
								material=-1;
								name="gunner_turret_hit";
								visual="vez";
								passThrough=0;
								minimalHit=0.02;
								explosionShielding=0.30000001;
								radius=0.25;
							};
							class HitGun
							{
								armor=0.30000001;
								material=-1;
								name="gunner_turret_hit";
								visual="";
								passThrough=0;
								minimalHit=0;
								explosionShielding=1;
								radius=0.25;
							};
						};
						class Damage
						{
							tex[]={};
							mat[]=
							{
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_body.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_body_damage.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_body_destruct.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_int.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_int_damage.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_int_destruct.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_tow.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_tow_damage.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_tow_destruct.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_track.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_track_damage.rvmat",
								"A3\armor_f_gamma\MBT_01\Data\MBT_01_track_destruct.rvmat"
							};
						};
						selectionFireAnim="";
						gunBeg[]=
						{
							"konec_hlavne_1",
							"konec_hlavne_2"
						};
						gunEnd[]=
						{
							"usti_hlavne_1",
							"usti_hlavne_2"
						};
					};
				};
				gunBeg="usti hlavne";
				gunEnd="konec hlavne";
				proxyIndex=2;
				weapons[]=
				{
					"442_aat_cannon_75mm"
				};
				magazines[]=
				{
					"442_75_30rnd_ap_blue_mag",
					"442_75_30rnd_ap_blue_mag",
					"442_75_30rnd_ap_blue_mag",
					"442_75_30rnd_ap_blue_mag",
					"442_75_30rnd_ap_blue_mag"
				};
				minElev=-5;
				maxElev=30;
				initElev=10;
				minTurn=-360;
				maxTurn=360;
				soundServo[]=
				{
					"A3\Sounds_F\vehicles\armor\noises\servo_best",
					0.0099999998,
					1,
					50
				};
				turretInfoType="RscWeaponRangeZeroing";
				discreteDistance[]={100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400};
				discreteDistanceInitIndex=5;
				memoryPointGunnerOptics="gunnerview";
				gunnerOutOpticsModel="";
				gunnerOutOpticsEffect[]={};
				gunnerOpticsEffect[]={};
				gunnerForceOptics=1;
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"Ti"
						};
						thermalMode[]={4,5};
						gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Gunner_MTB_02_w_F.p3d";
						gunnerOpticsEffect[]={};
					};
					class Medium: Wide
					{
						gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Gunner_MTB_02_m_F.p3d";
						initFov=0.07;
						minFov=0.07;
						maxFov=0.07;
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Gunner_MTB_02_n_F.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
				gunnerAction="mbt2_slot2a_out";
				gunnerInAction="mbt2_slot2a_in";
				forceHideGunner=0;
				inGunnerMayFire=1;
				viewGunnerInExternal=1;
				class HitPoints
				{
					class HitTurret
					{
						armor=0.80000001;
						material=-1;
						name="main_turret_hit";
						visual="vez";
						passThrough=0;
						minimalHit=0.02;
						explosionShielding=0.30000001;
						radius=0.25;
					};
					class HitGun
					{
						armor=0.30000001;
						material=-1;
						name="main_gun_hit";
						visual="";
						passThrough=0;
						minimalHit=0;
						explosionShielding=1;
						radius=0.25;
					};
				};
			};
		};